### ISSUE TITLE
Add filesystem / dummy client

### ISSUE THREAD

**Issue by dillonwilliams** [innolitics/pacsman#3]
So that `pacsman` users can test without initially connecting to a PACS, we need a "dummy" client which returns local data from the local filesystem (and possibly stores data there too). 

Potential scope, in increasing order of flexibility:
1) Client serves a handful of hard-coded static data for narrow testing purposes 
2) Client serves static data with ID metadata coming from file and directory names, enabling user to add data to the filesystem on top of what's packaged with `pacsman` 
3) Client uses `pynetdicom` to load all *.dcm files in a directory, reading ID metadata from the files. This makes dynamic adding of data (for when we add `send_dataset_to_pacs` functionality) trivial.

The third option is probably the best unless the additional `pynetdicom` dependency needs to be avoided.

**Comment by johndgiese** [comment]
I definitely think option (3) is the best.

We can load the dicom files using `pydicom`, which is almost certainly going to be a hard dependency anyway.

I looked through the abstract methods on the `DicomInterface` class, and it seems like all of them should be simple to implement using a file system.  I think the constructor for the interface should take a directory name, which it can use to store/read the DICOM files.  This will allow us to construct a new `FileSystemDicomInterface` for each test case, if we wanted to, by passing in temporary directory names.  It also makes it easy to point to a directory which already contains DICOM files.

Perhaps initially, when we search for a patient or a study, we can loop through all of the files in the folder.  In other words, we can skip keeping a cache of data that is pre-read upon initialization, and can loop through the files every time.  This will be slow if we have a lot of files, however, we probably won't ever have a lot of files since this is just a testing tool.

**Comment by johndgiese** [comment]
@yujanshrestha what are your thoughts on this issue?

**Comment by yujanshrestha** [comment]
> Client uses pynetdicom to load all *.dcm files in a directory, reading ID metadata from the files. This makes dynamic adding of data (for when we add send_dataset_to_pacs functionality) trivial.

Did you mean `pydicom` instead of `pynetdicom`?

If so, I think option (3) is the best. This has been a use case for dev purposes for quite some time now.

**Comment by dillonwilliams** [comment]
Merged. It implements the more flexible option 3 using DICOM files.

**Comment by dillonwilliams** [comment]
This looks good for now.
